name: Create and publish the Cypress Docker image

on:
  push:
    branches:
      - [main, add_docker]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: cypress-tests
  DOCKER_REGISTRY: filipgavrilovski

jobs:
  push_to_registry:
    name: Push Cypress image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: |
          echo ${{ env.SHA }}
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }} -f Dockerfile .
      - name: Push to Docker Container
        id: docker
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
