name: Cypress Integration Tests

on:
  repository_dispatch:
    types: [cypress-dev]
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: 'cypress-integration'
  cancel-in-progress: false

jobs:
  run_tests:
    name: UI Integration Specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --config-file cypress.config.js
          browser: electron
          group: 'All Specs'
      - name: Uploading test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Api Tests Report - RTC
          path: cypress/reports/Report.html
          retention-days: 30
